version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=hotel_data
      - POSTGRES_USER=brandon
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

